id = 2938
title = "10.0.0 HVF x86_64 regression: can't boot NetBSD 10.1 with -smp 2"
state = "opened"
created_at = "2025-04-28T18:35:47.768Z"
closed_at = "n/a"
labels = ["accel: HVF", "guest: BSD", "target: arm"]
url = "https://gitlab.com/qemu-project/qemu/-/issues/2938"
host-os = "macOS 15.4.1"
host-arch = "x86_64"
qemu-version = "10.0.0 (built from pkgsrc)"
guest-os = "NetBSD 10.1"
guest-arch = "amd64"
description = """Under 9.2.3, a NetBSD/amd64 10.1 guest with `-smp 2` booted and ran fine.

Under 10.0.0, the same guest never finishes loading the kernel. It looks like it's retrying many times per second, possibly even reloading the NetBSD boot loader each time, though it's redrawing so fast I can't tell for sure. (I'll attempt to link to an asciinema capture shortly.) `-smp 1` lets the machine come up.

For comparison, a NetBSD/aarch64 10.1 with `-smp 4` runs with `-accel hvf` under macOS/aarch64 15.4.1 just as well with 10.0.0 as it did with 9.2.3."""
reproduce = """1. With x86 macOS host and NetBSD guest (possibly a wider range than the exact versions I'm currently using), attempt to boot NetBSD with `-smp 2`"""
additional = """"""
