id = 2826
title = "The host PCI bridge disappeared on the big endian MIPS Malta machine"
state = "opened"
created_at = "2025-02-21T14:44:01.961Z"
closed_at = "n/a"
labels = ["kind::Bug", "target: mips"]
url = "https://gitlab.com/qemu-project/qemu/-/issues/2826"
host-os = "Linux"
host-arch = "x86_64"
qemu-version = "Current head (commit 40efe733e10cc00e4)"
guest-os = "Linux"
guest-arch = "mips (32-bit big endian)"
description = """The tests/avocado/linux_ssh_mips_malta.py test currently fails for the big endian machines. It tries to check for the PCI host bridge with ``lspci -d 11ab:4620``, but that does not show the expected output anymore -- it looks like the host bridge cannot be correctly discovered by the guest Linux kernel anymore."""
reproduce = """1. Get the kernel and disk image from https://people.debian.org/~aurel32/qemu/mips/
2. Boot the guest as described above.
3. lspci -d 11ab:4620"""
additional = """This used to work fine before commit 145e2198d749ec09a405f1607a9932499b76f1eb , so this rework likely introduced the bug. Looking at the code that got removed there, I could see an additional check ``phb->config_reg & 0x00fff800`` that is not present in the new code anymore, so the space for the host bridge itself likely should not get swapped. Reverting 3d85c7c15fc7ce986cf1a8e73da1217228f35685 and 145e2198d749ec09a405f1607a9932499b76f1eb seems to fix the problem (at least on little endian hosts)."""
