id = 2189
title = "vhost_user:When configure queues of vhost-user NIC exceeds max_queues, the virtual machine is always paused"
state = "opened"
created_at = "2024-02-23T07:45:26.132Z"
closed_at = "n/a"
labels = []
url = "https://gitlab.com/qemu-project/qemu/-/issues/2189"
host-os = "- Architecture:"
host-arch = "## Description of problem"
qemu-version = "n/a"
guest-os = "- Architecture:"
guest-arch = "## Description of problem"
description = """When the virtual machine uses the vhost-user network card and sets the queue number of the network card to exceed the maximum number of supported queues, the virtual machine fails to start and stays in the paused state.
And the virtual machine log file kept print "qemu - system - x86_64: -netdev host-user,chardev=charnet0,queues=5,id=hostnet0:you are asking more queues than supported:4â€"""
reproduce = """1.Configure vhost-user network cards for VMS and use multiple queues.
2.The number of NIC queues configured in the VM xml file is greater than the maximum number of queues supported by the VM, that is, the number of Vcpus on the VM.
3.Execute "virsh create VM_xml_file" cmd to start VM."""
additional = """According to normal logic, if the number of configured vhost-user NIC queues exceeds max-queues, the qemu process should be stopped, rather than paused the virtual machine.
I am confused about this patch:https://github.com/qemu/qemu/commit/c89804d674e4e3804bd3ac1fe79650896044b4e8
The process will remain in the do...while loop, when vhost_user_start is called in net_vhost_user_event, if queues > max_queues in vhost_user_start.
/label ~"kind::Bug"
```"""
