id = 2933
title = "After updating QEMU to 10.0, XNU kernel of OS X 10.8 throws kernel panic (type=0 divide error)"
state = "opened"
created_at = "2025-04-25T14:37:26.524Z"
closed_at = "n/a"
labels = []
url = "https://gitlab.com/qemu-project/qemu/-/issues/2933"
host-os = "macOS 15"
host-arch = "ARM64"
qemu-version = "QEMU emulator version 10.0.0"
guest-os = "OS X 10.8"
guest-arch = "x86_64"
description = """Before updating to QEMU 10.0, my OS X 10.8 installation has worked pretty clear, but after QEMU update, XNU kernel now throws divide error during the boot."""
reproduce = """1. Install OS X 10.8 on QEMU <10.0, for example 9.2.3.
2. Update QEMU to 10.0 version
3. Launch OS X"""
additional = """Screenshot of the issue:
![Screenshot_2025-04-25_at_17.29.51](/uploads/b961258103a778ed8f12d036b3518eeb/Screenshot_2025-04-25_at_17.29.51.png)

OpenCore config (not changed before update, so above suspicion):
[config.plist](/uploads/4b80b60f9497e5ecd9237e4eeddcce8a/config.plist)

Full OS X folder (without Installer.dmg):
[OS_X_10.8.zip](/uploads/1af6150869495a8f196e18d18127011b/OS_X_10.8.zip)

How I've done Installer.dmg:
1. Go [here](https://updates.cdn-apple.com/2021/macos/031-0627-20210614-90D11F33-1A65-42DD-BBEA-E1D9F43A6B3F/InstallMacOSX.dmg)
2. `xar -xf` to .pkg
3. Show package contents to extracted .pkg
4. Here it is: InstallESD.dmg, which I've renamed to Installer.dmg"""
