id = 2966
title = "KVM: Failed to create TCE64 table for liobn 0x80000001"
state = "opened"
created_at = "2025-05-15T15:49:03.835Z"
closed_at = "n/a"
labels = []
url = "https://gitlab.com/qemu-project/qemu/-/issues/2966"
host-os = "Fedora 42"
host-arch = "ppc64le"
qemu-version = "QEMU emulator version 9.2.3 (qemu-9.2.3-1.fc42)"
guest-os = "CentOS Stream 10"
guest-arch = "ppc64"
description = """When rebooting the system we hit :
   ```
   KVM: Failed to create TCE64 table for liobn 0x80000001
   qemu-system-ppc64: ../system/memory.c:2666: memory_region_add_subregion_common: Assertion `!subregion->container' failed.
   Aborted (core dumped)
   ```"""
reproduce = """1. Start the machine
2. Reboot it
 
   ```
   curl -LO https://cloud.centos.org/centos/10-stream/ppc64le/images/CentOS-Stream-GenericCloud-10-20250512.0.ppc64le.qcow2
   export LIBGUESTFS_BACKEND=direct
   virt-customize -v -a CentOS-Stream-GenericCloud-10-20250512.0.ppc64le.qcow2 --root-password password:centos
   qemu-system-ppc64 --enable-kvm -m 4096 -smp 8 -hda CentOS-Stream-GenericCloud-10-20250512.0.ppc64le.qcow2 -vga none -nographic -device qemu-xhci
   # once logged into it
   systemctl reboot
   [...]
   KVM: Failed to create TCE64 table for liobn 0x80000001
   qemu-system-ppc64: ../system/memory.c:2666: memory_region_add_subregion_common: Assertion `!subregion->container' failed.
   Aborted (core dumped)
   ```"""
additional = """The issue was already reported on ML https://lists.nongnu.org/archive/html/qemu-devel/2025-03/msg05137.html  
I also hit that issue while building a CoreOS CentOS Stream 10 image https://github.com/openshift/os/issues/1818. I was able to validate that the commit https://github.com/torvalds/linux/commit/6aa989ab2bd0d37540c812b4270006ff794662e7 introduced the bug."""
